# ================================================================
# gemb_CD_endogenousClaimRateBudget_nc3_na4_v2.jl
#
# High-level GEMB example:
# endogenous ad valorem claim rate determined by government
# budget balance through a ConditionAgentSpec tax-rate setter.
#
# No GEMB claim_rate machinery is used by the firm.
#
# Commodities:
#   1. prod
#   2. lab
#   3. tax_certificate
#
# Agents:
#   1. taxRateSetter   (virtual policy agent)
#   2. firm
#   3. household
#   4. government
#
# Firm technology:
#
#     y = prod^0.5 * lab^0.5
#
# Household preferences:
#
#     u = prod^0.8 * lab^0.2
#
# Household endowment:
#
#     100 units of labor
#
# Government:
#
#     supplies 20 tax certificates
#     purchases 20 units of labor
#
# The virtual tax-rate setter chooses tau so that
#
#     tau * firm ordinary input expenditure
#         = government labor expenditure.
#
# The firm observes tau and directly computes tax-certificate demand:
#
#     q_tax = tau * base_cost / p_tax.
#
# Hence
#
#     p_tax * q_tax = tau * base_cost,
#
# and government budget balance is enforced by the virtual-agent
# condition.
#
# Expected equilibrium:
#
#     p_prod = 1
#     p_lab = p_tax = 9 / 49
#     tau = 1 / 6
#     firm activity = 180 / 7
#     firm tax-certificate demand = 20
#
# V2 uses ConditionAgentSpec for the policy variable.
# This file solves immediately when included.
# ================================================================

using GeneralEquilibriumModeling.GEM
using GeneralEquilibriumModeling.GEMB


# ----------------------------------------------------------------
# 1. Parameters
# ----------------------------------------------------------------

const LABOR_ENDOWMENT = 100.0
const GOVERNMENT_LABOR_DEMAND = 20.0
const TAX_CERTIFICATE_SUPPLY = 20.0

const BETA_FIRM = [0.5, 0.5]
const BETA_HOUSEHOLD = [0.8, 0.2]


# ----------------------------------------------------------------
# 2. Model
# ----------------------------------------------------------------

model = GEMBModel(
    [
        :prod,
        CommoditySpec(
            :lab;
            price_lower_bound=1.0e-10,
        ),
        CommoditySpec(
            :tax_certificate;
            price_lower_bound=1.0e-10,
        ),
    ];
    numeraire=:prod,
    numeraire_value=1.0,
)


# ----------------------------------------------------------------
# 3. Virtual tax-rate setter
#
# ConditionAgentSpec gives the virtual policy agent one endogenous
# variable with no economic commodity demand or supply:
#
#     tax_rate = tau.
#
# It observes:
#
#   observed_values[1] = p_prod
#   observed_values[2] = p_lab
#   observed_values[3] = firm activity
#
# and imposes government budget balance:
#
#     tau * total ordinary input expenditure
#       - p_lab * government labor demand
#       = 0.
#
# The reference to :firm is intentionally a forward reference.
# GEMB resolves structured agent references when the model is built.
# The zero-net-supply adaptation is handled internally by GEMB.
# ----------------------------------------------------------------

tax_rate_setter_spec = ConditionAgentSpec(
    (
        variables,
        observed_values,
    ) -> begin
        tau = variables[1]

        p_prod = observed_values[1]
        p_lab = observed_values[2]
        firm_activity = observed_values[3]

        unit_base_cost = GEMB.CES_cost(
            BETA_FIRM,
            1.0,
            [
                p_prod,
                p_lab,
            ];
            es=1.0,
            alpha=1.0,
        )

        total_base_cost =
            firm_activity *
            unit_base_cost

        government_expenditure =
            GOVERNMENT_LABOR_DEMAND *
            p_lab

        return [
            tau * total_base_cost -
            government_expenditure,
        ]
    end,
)

taxRateSetter = add_agent!(
    model,
    tax_rate_setter_spec;
    variable_names=:tax_rate,
    variable_start=1.0 / 6.0,
    variable_lower_bounds=-Inf,
    variable_upper_bounds=Inf,
    observed_variables=[
        PriceVariableRef(:prod),
        PriceVariableRef(:lab),
        agent_variable_ref(
            :firm,
            :activity,
        ),
    ],
    name=:taxRateSetter,
)


# ----------------------------------------------------------------
# 4. Firm
#
# The firm observes the endogenous tau from taxRateSetter.
#
# It first computes ordinary Cobb--Douglas inputs. Their value is the
# ad valorem claim base:
#
#     base_cost = p_prod * x_prod + p_lab * x_lab.
#
# It then directly computes tax-certificate demand:
#
#     q_tax = tau * base_cost / p_tax.
#
# Therefore
#
#     p_tax * q_tax = tau * base_cost.
#
# The existing UnitRevenueExpenditureBalanceConditions generated by ActivityDemandSpec
# automatically includes this tax-certificate expenditure in the
# firm's unit-loss condition.
# ----------------------------------------------------------------

firm_spec = ActivityDemandSpec(
    (
        activity,
        prices,
        observed_values,
    ) -> begin
        p_prod, p_lab, p_tax = prices
        tau = observed_values[1]

        ordinary_inputs = GEMB.CES_input(
            BETA_FIRM,
            activity,
            [
                p_prod,
                p_lab,
            ];
            es=1.0,
            alpha=1.0,
        )

        base_cost =
            p_prod * ordinary_inputs[1] +
            p_lab * ordinary_inputs[2]

        tax_certificate_demand =
            tau *
            base_cost /
            p_tax

        return [
            ordinary_inputs[1],
            ordinary_inputs[2],
            tax_certificate_demand,
        ]
    end,
)

firm = add_agent!(
    model,
    firm_spec;
    outputs=:prod,
    demands=[
        :prod,
        :lab,
        :tax_certificate,
    ],
    observed_variables=[
        agent_variable_ref(
            :taxRateSetter,
            :tax_rate,
        ),
    ],
    activity_start=180.0 / 7.0,
    name=:firm,
)


# ----------------------------------------------------------------
# 5. Household
#
# The household owns 100 units of labor and has Cobb--Douglas
# Marshallian demand over prod and lab.
# ----------------------------------------------------------------

household_spec = MarshallDemandConsumerSpec(
    function (income, prices)
        p_prod, p_lab = prices

        return [
            BETA_HOUSEHOLD[1] * income / p_prod,
            BETA_HOUSEHOLD[2] * income / p_lab,
        ]
    end,
)

household = add_agent!(
    model,
    household_spec;
    demands=[
        :prod,
        :lab,
    ],
    endowments=:lab,
    endowment_quantities=LABOR_ENDOWMENT,
    name=:household,
)


# ----------------------------------------------------------------
# 6. Government
#
# The government supplies tax certificates and purchases a fixed
# quantity of labor.
#
# Its budget balance is not imposed inside this demand function.
# Instead, taxRateSetter adjusts tau until
#
#     value of tax-certificate revenue
#       = value of government labor purchases.
#
# At equilibrium:
#
#     p_tax * TAX_CERTIFICATE_SUPPLY
#       = p_lab * GOVERNMENT_LABOR_DEMAND.
# ----------------------------------------------------------------

government_spec = MarshallDemandConsumerSpec(
    function (income, prices)
        return [
            GOVERNMENT_LABOR_DEMAND,
        ]
    end,
)

government = add_agent!(
    model,
    government_spec;
    demands=:lab,
    endowments=:tax_certificate,
    endowment_quantities=TAX_CERTIFICATE_SUPPLY,
    name=:government,
)


# ----------------------------------------------------------------
# 7. Solve
# ----------------------------------------------------------------

result = solve(
    model;
    p0=[
        1.0,
        0.18,
        0.18,
    ],
    residual_tol=1.0e-8,
    silent=true,
)


# ----------------------------------------------------------------
# 8. Results
# ----------------------------------------------------------------

endogenous_tau =
    result.agent_variable_values[1][1]

firm_activity =
    result.agent_variable_values[2][1]

firm_tax_certificate_demand =
    -result.agent_net_supplies[2][3]

p_prod, p_lab, p_tax =
    result.prices

unit_base_cost = GEMB.CES_cost(
    BETA_FIRM,
    1.0,
    [
        p_prod,
        p_lab,
    ];
    es=1.0,
    alpha=1.0,
)

total_base_cost =
    firm_activity *
    unit_base_cost

tax_revenue =
    endogenous_tau *
    total_base_cost

tax_certificate_revenue =
    p_tax *
    firm_tax_certificate_demand

government_expenditure =
    p_lab *
    GOVERNMENT_LABOR_DEMAND

budget_gap =
    tax_revenue -
    government_expenditure


println()
println(
    "========== GEMB endogenous claim rate: government budget balance ==========",
)

println(
    "Solved:                              ",
    result.solved,
)

println(
    "Prices [prod, lab, tax certificate]: ",
    result.prices,
)

println(
    "Endogenous claim rate tau:           ",
    endogenous_tau,
)

println(
    "Firm activity:                       ",
    firm_activity,
)

println(
    "Unit ordinary input cost:            ",
    unit_base_cost,
)

println(
    "Total ordinary input expenditure:    ",
    total_base_cost,
)

println(
    "Firm tax-certificate demand:         ",
    firm_tax_certificate_demand,
)

println(
    "Tax revenue tau * base:              ",
    tax_revenue,
)

println(
    "Tax-certificate revenue:             ",
    tax_certificate_revenue,
)

println(
    "Government labor expenditure:        ",
    government_expenditure,
)

println(
    "Government budget gap:               ",
    budget_gap,
)

println(
    "Tax-rate-setter net supply:          ",
    result.agent_net_supplies[1],
)

println(
    "Firm net supply:                     ",
    result.agent_net_supplies[2],
)

println(
    "Household net supply:                ",
    result.agent_net_supplies[3],
)

println(
    "Government net supply:               ",
    result.agent_net_supplies[4],
)

println(
    "Total net supply:                    ",
    result.total_net_supply,
)

println(
    "Max natural residual:                ",
    result.max_natural_residual,
)

println(
    "===========================================================================",
)


# ----------------------------------------------------------------
# 9. Benchmark checks
# ----------------------------------------------------------------

expected_prices = [
    1.0,
    9.0 / 49.0,
    9.0 / 49.0,
]

expected_tau =
    1.0 / 6.0

expected_firm_activity =
    180.0 / 7.0


@assert result.solved
@assert result.mcp_solved
@assert result.all_markets_clear

@assert isapprox(
    result.prices,
    expected_prices;
    atol=1.0e-7,
    rtol=1.0e-7,
)

@assert isapprox(
    endogenous_tau,
    expected_tau;
    atol=1.0e-7,
    rtol=1.0e-7,
)

@assert isapprox(
    firm_activity,
    expected_firm_activity;
    atol=1.0e-7,
    rtol=1.0e-7,
)

@assert isapprox(
    firm_tax_certificate_demand,
    TAX_CERTIFICATE_SUPPLY;
    atol=1.0e-7,
    rtol=1.0e-7,
)

@assert isapprox(
    tax_revenue,
    tax_certificate_revenue;
    atol=1.0e-7,
    rtol=1.0e-7,
)

@assert isapprox(
    tax_revenue,
    government_expenditure;
    atol=1.0e-7,
    rtol=1.0e-7,
)

@assert abs(
    budget_gap,
) <= 1.0e-7

@assert maximum(
    abs,
    result.agent_net_supplies[1],
) <= 1.0e-7

@assert maximum(
    abs,
    result.total_net_supply,
) <= 1.0e-7

@assert result.max_natural_residual <= 1.0e-7
